version: '3.8'

networks:
  default:
    external:
      name: my-interservice-network

services:
  echo-server:
    build: .
    ports:
    - "8000:8000"
    tty: true
    environment:
      - DATABASE_HOSTNAME=database
      - DATABASE_PORT=5432

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password