version: '3.8'

services:
  echo-server:
    build: .
    ports:
    - "8000:8000"
    tty: true
    command:
      watchmedo auto-restart --patterns "*.py" --recursive --
      python echo.py
    volumes:
      - .:/app/
