version: '3.8'

services:
  echo-server:
    build: .
    ports:
    - "8000:8000"
    tty: true
    depends_on:
      - database
    command:
      wait-for-it --service database:5432 --
      python echo.py

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
